#!/usr/bin/env bash
m="\e[0;31m" # merah
k="\e[0;33m" # kuning
h="\e[0;32m" # hijau
b="\e[0;34m" # biru
lm="\e[1;31m" # merah terang
lk="\e[1;33m" # kuning terang
lh="\e[1;32m" # hijau terang
lb="\e[1;34m" # langit biru
n="\e[0m" # netral
clear
function os() {

echo -e "${lb}
    ＜￣｀ヽ、　　　　　　　／￣＞
ゝ、　　＼　／⌒ヽ,ノ 　/´
ゝ、　`         （ ( ͡° ͜ʖ ͡°) ／
>　                    　,ノ
∠_,,,/´”                    $version 2.4.1

${n}"
echo -e "${m}   Crack Interface LockScreen${n}"
echo -e "${m}       Android/IOS Hacking${n}"
echo -e "${lb}    Github Wharkly-47 - Wharkly${n}"
}

banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner

echo "Please Wait.   / "
sleep 0.5
clear
banner

echo "Please Wait..  | "
sleep 0.5
clear
banner

echo "Please Wait... \ "
sleep 0.5
clear
banner
